# -*- coding: utf-8 -*-
"""4301_AirPressure.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KO0NR_TyueGOfj0p22J5_F-XzxtmYDBj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load data into a pandas DataFrame
data = pd.read_csv('/content/ronald_15Feb.csv',index_col=False)

#df_time = pd.to_datetime(data["Date/Time"]).dt.second
#data = data.drop(data[data.LB > 500].index)
#data = data.drop(data[data.RB > 500].index)
#data = data.dropna(Axis="row")
#data = data.drop(index=0) #to remove initial 0 value sensor readings

#lb = data['LeftButt'] #Jocillia formatting
#rb = data['RightButt'] #joc formatting

lb = data['Left_Butt'] #Jocillia formatting
rb = data['Right_Butt']

data

fig, (ax1, ax2, ax3) = plt.subplots(3, 1,figsize=(30,15))

ax1.plot(data.index,lb)
ax1.set(xlabel='time (s)',ylabel='Airpressure_LeftButt (kPA)')
ax1.xaxis.set_ticks(np.arange(0,10800,600)) #600 because discomfort ratings recorded every 10 minutes
#ax1.set_xlim(2,21600)

ax2.plot(data.index, rb)
ax2.set(xlabel='time (s)',ylabel='Airpressure_RightButt (kPA)')
ax2.xaxis.set_ticks(np.arange(2,10800,600))

ax3.plot(data.index, button)

#ax3.set_title('Button press')
ax3.set(xlabel='time (s)',ylabel='button')
ax3.xaxis.set_ticks(np.arange(0,10800,600))
plt.savefig('filename1.png',dpi=300)

#plt.xlim(7500,8000)
#plt.ylim(100,104)
#plt.scatter(data.index,button)
#plt.title('Scatter Plot')
#plt.xlabel('X Axis')
#plt.ylabel('Y Axis')


#ax_1 = data.reset_index().plot.scatter(x='index',y='Butt_Inflate_B3')
#ax_2 = data.reset_index().plot.scatter(x='index',y='Upper_Inflate_B5')

#ax1.set_xlim(5800,6000)
#ax2.set_xlim(7500,8000)

data.plot.line(use_index=True,y='Left_Butt')

data.plot.line(use_index=True,y='Right_Butt')
data.reset_index().plot.scatter(x='index',y='Butt_Inflate_B3')



